import type { ModelDefinition } from "@/models.js";

export const zaiModels = [
	{
		id: "glm-5",
		name: "GLM-5",
		description: "Zhipu GLM-5 with advanced reasoning capabilities.",
		family: "glm",
		releasedAt: new Date("2026-02-15"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-5",
				inputPrice: 1 / 1e6,
				cachedInputPrice: 0.2 / 1e6,
				outputPrice: 3.2 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 202800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01,
				jsonOutput: true,
			},
			{
				providerId: "canopywave",
				test: "skip",
				modelName: "zai/glm-5",
				inputPrice: 0.9 / 1e6,
				cachedInputPrice: 0.2 / 1e6,
				outputPrice: 3.1 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: false,
			},
			{
				providerId: "together.ai",
				modelName: "zai-org/GLM-5",
				inputPrice: 1 / 1e6,
				outputPrice: 3.2 / 1e6,
				requestPrice: 0,
				contextSize: 202752,
				maxOutput: 202752,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "novita",
				modelName: "zai-org/glm-5",
				inputPrice: 1 / 1e6,
				cachedInputPrice: 0.2 / 1e6,
				outputPrice: 3.2 / 1e6,
				requestPrice: 0,
				contextSize: 202800,
				maxOutput: 131100,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5",
		name: "GLM-4.5",
		description: "Zhipu GLM-4.5 with reasoning capabilities.",
		family: "glm",
		releasedAt: new Date("2025-07-28"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.11 / 1e6,
				outputPrice: 2.2 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $0.01 per search
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5v",
		name: "GLM-4.5V",
		description: "GLM-4.5 with vision support.",
		family: "glm",
		releasedAt: new Date("2025-08-11"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5v",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.11 / 1e6,
				outputPrice: 1.8 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "zai-org/glm-4.5v",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.11 / 1e6,
				outputPrice: 1.8 / 1e6,
				requestPrice: 0,
				contextSize: 65536,
				maxOutput: 16000,
				streaming: true,
				reasoning: true,
				reasoningOutput: "omit",
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5-air",
		name: "GLM-4.5 Air",
		description: "Lightweight GLM-4.5 variant.",
		family: "glm",
		releasedAt: new Date("2025-07-25"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-air",
				inputPrice: 0.2 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				outputPrice: 1.1 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: false,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5-x",
		name: "GLM-4.5 X",
		description: "Extended GLM-4.5 with advanced reasoning.",
		family: "glm",
		releasedAt: new Date("2025-07-28"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-x",
				inputPrice: 2.2 / 1e6,
				cachedInputPrice: 0.45 / 1e6,
				outputPrice: 8.9 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				stability: "unstable", // unstable due to high limits
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5-airx",
		name: "GLM-4.5 AirX",
		description: "Enhanced GLM-4.5 Air variant.",
		family: "glm",
		releasedAt: new Date("2025-07-28"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-airx",
				inputPrice: 1.1 / 1e6,
				cachedInputPrice: 0.22 / 1e6,
				outputPrice: 4.5 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: false,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.5-flash",
		name: "GLM-4.5 Flash",
		description: "Free, fast GLM-4.5 model.",
		family: "glm",
		free: true,
		releasedAt: new Date("2025-08-13"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.5-flash",
				inputPrice: 0,
				cachedInputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: false,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.7",
		name: "GLM-4.7",
		description: "Latest GLM with enhanced reasoning capabilities.",
		family: "glm",
		releasedAt: new Date("2025-12-22"),
		providers: [
			{
				providerId: "zai",
				test: "skip",
				modelName: "glm-4.7",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.11 / 1e6,
				outputPrice: 2.2 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $0.01 per search
				jsonOutput: true,
			},
			{
				providerId: "canopywave",
				modelName: "zai/glm-4.7",
				inputPrice: 0.43 / 1e6,
				outputPrice: 1.75 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				test: "skip", // skip tests due to reasoning issues
				modelName: "zai-org/glm-4.7",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.11 / 1e6,
				outputPrice: 2.2 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				// Cerebras: FP16/FP8 (weights only)
				providerId: "cerebras",
				test: "skip",
				modelName: "zai-glm-4.7",
				inputPrice: 2.25 / 1e6,
				outputPrice: 2.75 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				supportedParameters: [
					"temperature",
					"max_tokens",
					"top_p",
					"response_format",
					"tools",
					"tool_choice",
				],
			},
			{
				providerId: "bytedance",
				modelName: "glm-4-7-251222",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.11 / 1e6,
				outputPrice: 2.2 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: false, // Returns JSON wrapped in markdown code blocks
			},
			{
				providerId: "together.ai",
				modelName: "zai-org/GLM-4.7",
				inputPrice: 0.45 / 1e6,
				outputPrice: 2.0 / 1e6,
				requestPrice: 0,
				contextSize: 202752,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "glm-4.7-flashx",
		name: "GLM-4.7 FlashX",
		description: "Lightweight, high-speed GLM-4.7 variant.",
		family: "glm",
		releasedAt: new Date("2025-12-22"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.7-flashx",
				inputPrice: 0.07 / 1e6,
				cachedInputPrice: 0.01 / 1e6,
				outputPrice: 0.4 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.7-flash",
		name: "GLM-4.7 Flash",
		description: "Free, lightweight GLM-4.7 model.",
		family: "glm",
		free: true,
		releasedAt: new Date("2025-12-22"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.7-flash",
				inputPrice: 0,
				cachedInputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: 128000,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.6",
		name: "GLM-4.6",
		description: "Updated GLM with reasoning capabilities.",
		family: "glm",
		releasedAt: new Date("2025-09-30"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.6",
				inputPrice: 0.6 / 1e6,
				cachedInputPrice: 0.11 / 1e6,
				outputPrice: 2.2 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.01, // $0.01 per search
				jsonOutput: true,
			},
			{
				// Cerebras: FP16/FP8 (weights only)
				providerId: "cerebras",
				test: "skip",
				deactivatedAt: new Date("2026-01-20"),
				modelName: "zai-glm-4.6",
				inputPrice: 2.25 / 1e6,
				outputPrice: 2.75 / 1e6,
				requestPrice: 0,
				contextSize: 200000,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "canopywave",
				deactivatedAt: new Date("2026-01-01"),
				modelName: "zai/glm-4.6",
				inputPrice: 0.45 / 1e6,
				outputPrice: 1.5 / 1e6,
				discount: 0.3,
				requestPrice: 0,
				contextSize: 202752,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				test: "skip",
				modelName: "zai-org/glm-4.6",
				inputPrice: 0.55 / 1e6,
				cachedInputPrice: 0.11 / 1e6,
				outputPrice: 2.2 / 1e6,
				requestPrice: 0,
				contextSize: 204800,
				maxOutput: undefined,
				streaming: true,
				reasoning: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4-32b-0414-128k",
		name: "GLM-4 32B (0414-128k)",
		description: "GLM-4 32B instruction-tuned model.",
		family: "glm",
		releasedAt: new Date("2025-04-14"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4-32b-0414-128k",
				inputPrice: 0.1 / 1e6,
				cachedInputPrice: 0,
				outputPrice: 0.1 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				reasoning: false,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.6v",
		name: "GLM-4.6V",
		description:
			"Flagship vision-language model (106B) with native function calling support.",
		family: "glm",
		releasedAt: new Date("2025-12-08"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.6v",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.05 / 1e6,
				outputPrice: 0.9 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16000,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "novita",
				modelName: "zai-org/glm-4.6v",
				inputPrice: 0.3 / 1e6,
				cachedInputPrice: 0.055 / 1e6,
				outputPrice: 0.9 / 1e6,
				requestPrice: 0,
				contextSize: 131072,
				maxOutput: 16000,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.6v-flashx",
		name: "GLM-4.6V FlashX",
		description: "Fast vision-language model with extended capabilities.",
		family: "glm",
		releasedAt: new Date("2025-12-08"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.6v-flashx",
				inputPrice: 0.04 / 1e6,
				cachedInputPrice: 0.004 / 1e6,
				outputPrice: 0.4 / 1e6,
				discount: 0.1,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16000,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "glm-4.6v-flash",
		name: "GLM-4.6V Flash",
		description:
			"Ultra-fast, lightweight vision-language model (9B) for low-latency workloads.",
		family: "glm",
		free: true,
		releasedAt: new Date("2025-12-08"),
		providers: [
			{
				providerId: "zai",
				modelName: "glm-4.6v-flash",
				inputPrice: 0,
				cachedInputPrice: 0,
				outputPrice: 0,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 16000,
				streaming: true,
				reasoning: true,
				vision: true,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "cogview-4",
		name: "CogView-4",
		description:
			"Z.AI's CogView-4 text-to-image generation model with bilingual support and excellent text rendering.",
		family: "zai",
		output: ["text", "image"],
		releasedAt: new Date("2025-03-04"),
		providers: [
			{
				test: "skip",
				providerId: "zai",
				modelName: "cogView-4-250304",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0.01,
				discount: 0.1,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
		],
	},
	{
		id: "glm-image",
		name: "GLM-Image",
		description:
			"Z.AI's GLM-Image text-to-image generation model with hybrid auto-regressive architecture, excellent for text-rendering and knowledge-intensive generation.",
		family: "glm",
		output: ["text", "image"],
		releasedAt: new Date("2025-01-14"),
		providers: [
			{
				test: "skip",
				providerId: "zai",
				modelName: "glm-image",
				inputPrice: 0,
				outputPrice: 0,
				requestPrice: 0.015,
				discount: 0.1,
				contextSize: 2000,
				maxOutput: 4096,
				streaming: false,
				vision: false,
				tools: false,
				jsonOutput: false,
				imageGenerations: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
